project 'SpringOC.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SpringOC' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpringOC
  
  pod 'pop', '~> 1.0'
  
  #pod 'SnapKit', '~> 3.0.2'
  
  pod 'Masonry'

end
